site_name: TheArtorias site

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

  extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/TheArtoriass

  copyright: |
    &copy; 2023 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">James Willett</a>

nav : 
  - Home: index.md
  - test: partie_1.md

#pandoc -s -o partie_2.pdf partie_2.pdf